ChargeBackEthoca/Controllers/Stripe/StripeController.cs
using ChargeBackEthoca.Models.Component;
using ChargeBackEthoca.Models.Dao;
using ChargeBackEthoca.Repository;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChargeBackEthoca.Controllers.Stripe
{
    public class StripeController : Controller
    {
        Permisstion chkUser = new Permisstion();
        // GET: Stripe
        public ActionResult Index(int? page)
        {
            chkUser.chkrights("USER");
            Session["USERNAME"] = Varible.User.USERNAME;
            Session["CustomerId"] = Varible.User.CustomerId;
            Session["ROLE"] = Varible.User.MEMBER_ID;
            var Data = PaymentDao.Instance.ReqBilling();
            var count = Data.Count.ToString();
            TempData["data"] = Data.ToList().ToPagedList(page ?? 1, 10);
            Session["Count"] = count;
            ViewBag.Count = Session["Count"];
            return View(TempData["data"]);
        }
        public ActionResult Billing()
        {
            chkUser.chkrights("USER");
            string UID = Varible.User.USERNAME;
            Session["USERNAME"] = Varible.User.USERNAME;
            Session["CustomerId"] = Varible.User.CustomerId;
            Session["ROLE"] = Varible.User.MEMBER_ID;
            var DataUser = ProfileDao.Instance.GetDataUserById(UID);
            return View(DataUser);
        }
    }
}

ChargeBackEthoca/Views/Stripe/Billing.cshtml
@model IEnumerable<ChargeBackEthoca.Models.Dto.ProfileDto>
@{
    ViewBag.Title = "BILLING";
}
@Html.Hidden("Get", Url.Action("GetBilling", "Payment"))

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3 class="fontsmall">ChargeBackSafe</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>
                            BILLING
                            <small style="display: unset;">
                                <input class="ePay" type="button" onclick="ApiReq(this.value)" value="paid" style="background:none; border:none; color:forestgreen" />
                                <input class="ePay" type="button" onclick="ApiReq(this.value)" value="void " style="background:none; border:none; color:red" />
                            </small>
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive" style="height:800px">
                                    <table id="datatable" class="table table-striped table-bordered" style="width:200%">
                                        <thead>
                                            <tr>
                                                <th width="5%">ACTION</th>
                                                <th width="5%">OBJECT</th>
                                                <th>ACCOUNT COUNTRY</th>
                                                <th>ACCOUNT NAME</th>
                                                <th>AMOUNT DUE</th>
                                                <th>AMOUNT PAID</th>
                                                <th>CURRENCY</th>
                                                <th width="15%">CREATED</th>
                                                <th>AMOUNT REMAINNG</th>
                                                <th>FEE AMOUNT</th>
                                                <th>ATTEMPT COUNT</th>
                                                <th>ATTEMPT</th>
                                                <th>AUTO ADVANCE</th>
                                                <th>BILLING REASON</th>
                                                <th>CHARGE</th>
                                                <th>COLLECTION METHOD</th>
                                                <th>CUSTOMER</th>
                                                <th>CUSTOMER ADDRESS</th>
                                                <th>CUSTOMER EMAIL</th>
                                                @*<th>hosted_invoice_url</th>
                                                    <th>invoice_pdf</th>*@
                                            </tr>
                                        </thead>
                                        <tbody id="reponse_billing">
                                            <tr>
                                                <td colspan="19" class="text-center">No Data Request !!!</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Billing -->
<div class="modal fade" id="bil" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center">BILLING</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style=" height: 335px;">
                <span id="content_url" style="position: absolute; top: 40%; left: 32%; font-size: large; border: 1px solid; border-radius: 7px; padding: 10px;"></span>
            </div>
        </div>

    </div>
</div>
<input hidden value="@Session["UID"]" id="User" />
<input hidden value="@Session["CustomerId"]" id="customer" />
<script src="~/AppScript/billing.js"></script>

ChargeBackEthoca/Views/Stripe/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ChargeBackEthoca.Models.Dto.PaymentDto>
@{
    ViewBag.Title = "BILLING";
}


<!-- page content -->
<style>
    .pagination {
        display: flex;
        padding-left: 0;
        list-style: none;
        border-radius: .25rem;
        justify-content: end !important;
    }

        .pagination > li {
            padding: 15px !important;
            background: white;
        }

    .active {
        background: #149a8c !important;
        color: #fff;
    }
</style>
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3 class="fontsmall">ChargeBackSafe</h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div>
                <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#search" style="position: relative; left: 10px; top: 7px;">SEARCH</button>
            </div>
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>TRANSACION <small>LOG</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <table id="datatable" class="table table-striped table-bordered" style="width:130%">
                                        <tr>
                                            <th>NO.</th>
                                            <th>MANAGE</th>
                                            <th>URL</th>
                                            <th>OBJECT</th>
                                            <th>CUSMTOMER</th>
                                            <th>CREATE</th>
                                            <th>RETURN URL</th>
                                        </tr>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.ID</td>
                                                    <td><a href="@item.Url">BILLING</a></td>
                                                    <td>@item.Url</td>
                                                    <td>@item.objectBilling</td>
                                                    <td>@item.customer)</td>
                                                    <td>@item.create</td>
                                                    <td>@item.returnUrl</td>
                                                </tr>
                                            }
                                        }
                                    </table>
                                </div>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > 10)
                                {
                                    <div style="width:100%">
                                        @Html.PagedListPager(Model, Page => Url.Action("Index", "Stripe", new { Page }))
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->