ChargeBackEthoca/Controllers/Log/LogController.cs
using ChargeBackEthoca.Models.Component;
using ChargeBackEthoca.Models.Dao;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChargeBackEthoca.Controllers.Log
{
    public class LogController : Controller
    {
        Permisstion chkUser = new Permisstion();
        // GET: Log
        public ActionResult Index(int? page, string keyword)
        {
            chkUser.chkrights("USER");
            Session["USERNAME"] = Varible.User.USERNAME;
            Session["CustomerId"] = Varible.User.CustomerId;
            Session["ROLE"] = Varible.User.MEMBER_ID;
            var Data = LogDao.Instance.Log();
            var count = Data.Count.ToString();
            TempData["data"] = Data.ToList().ToPagedList(page ?? 1, 10);
            Session["Count"] = count;
            ViewBag.Count = Session["Count"];
            return View(TempData["data"]);
        }
    }
}

ChargeBackEthoca/Views/Log/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<ChargeBackEthoca.Models.Dto.LogDto>
@{
    ViewBag.Title = "LOG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Custom Theme Style -->
<link href="~/Content/css/Appcss1.css" rel="stylesheet" />

<style>
    .pagination {
        display: flex;
        padding-left: 0;
        list-style: none;
        border-radius: .25rem;
        justify-content: end !important;
    }

        .pagination > li {
            padding: 15px !important;
            background: white;
        }

    .active {
        background: #149a8c !important;
        color: #fff;
    }
</style>
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3 class="fontsmall">ChargeBackSafe</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button">Go!</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>LOG</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <table id="datatable" class="table table-striped table-bordered" style="width:130%; border: 1px solid #dee2e6;">
                                        <tr>
                                            <th>NO.</th>
                                            <th>IP</th>
                                            <th>BROWSER</th>
                                            <th>URL</th>
                                            <th>SYSTEM_OS</th>
                                            <th>CONNECTION_HARDWARE</th>
                                            <th>DATE</th>
                                        </tr>
                                        @if (Model != null && Model.Count() != 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.ID</td>
                                                    <td>@item.IP</td>
                                                    <td>@item.BROWSER</td>
                                                    <td>@item.URL</td>
                                                    <td>@item.SYSTEM_OS</td>
                                                    <td>@item.CONNECTION_HARDWARE</td>
                                                    <td>@item.DATE</td>
                                                </tr>

                                            }
                                        }
                                        else
                                        {
                                            <tr class="text-center">
                                                <td colspan="7">
                                                    No Data !!
                                                </td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </div>
                            @{
                                if (Convert.ToInt32(ViewBag.Count) > 10)
                                {
                                    <div style="width:100%">
                                        @Html.PagedListPager(Model, Page => Url.Action("Index", "Log", new { Page }))
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->